spring.application.name=cars
server.port=8084
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.endpoint.shutdown.enabled=true
//management.endpoints.web.exposure.include=*
management.security.enabled=true
spring.cache.type=simple
spring.cache.cache-names=Cars
spring.security.user.name=admin
spring.security.user.password=admin123
bank.defaultName=Axis Bank





